name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      AWS_REGION:    ${{ secrets.AWS_REGION }}
      ECR_REGISTRY:  ${{ vars.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
      IMAGE_TAG:     ${{ github.event.workflow_run.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install CDKTF dependencies
        working-directory: iac
        run: npm ci

      - name: Deploy infra with CDKTF
        working-directory: iac
        run: |
          # if your CDKTF stack reads IMAGE_TAG, ECR_REGISTRY & ECR_REPOSITORY from process.env,
          # this will pick them up automatically:
          npx cdktf deploy --auto-approve
